"""2fa models

Revision ID: 5a4ce8f85bb6
Revises: 
Create Date: 2024-05-07 01:45:24.746873

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.model.user import AuthTypeEnum


# revision identifiers, used by Alembic.
revision = '5a4ce8f85bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    AuthTypeEnum.create(op.get_bind(), checkfirst=True)

    op.create_table('users',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(
                        length=255), nullable=True),
                    sa.Column('phone_no', sa.String(length=24), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
                    sa.Column('auth_2fa_type', AuthTypeEnum, nullable=True),
                    sa.Column('otp_secret', sa.String(), nullable=True),
                    sa.Column('otp_auth_url', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    AuthTypeEnum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
